index.html styled as lo-fi wireframe
NoroffFEU/ai-project pull request #71
Opened 2024-03-20 10:52 UTC by cecsun

2024-03-20 19:16 UTC, ftmkrtgz approved these changes

2024-03-20 19:17 UTC, ftmkrtgz commented
Today's task page was built with bootstrap without any problems. Screen display up to 600 px is great.

2024-03-20 19:17 UTC, EF-Pami requested changes
Hi Cecsun, the styling codes are goods but if we take a look at the design we realized some of the color palettes have been modify with the codes.

The logout, add tasks and export task buttons are all having a white background color in the design.

Also the nav-pills coloumn is having rgba(218, 218, 218, 1) as the color in the design.

Guess we can modify this stylings.

2024-03-21 09:39 UTC, cecsun commented
@EF-Pami I only did the colors so it wouldn't just be white and grey, only for fun because it's a lo-fi wireframe. Hopefully you can approve, and it can be changed when design has updated a more complete wireframe for the design.

2024-03-21 09:52 UTC, EF-Pami approved these changes

2024-03-21 09:54 UTC, merged